# Generated by Django 5.2.4 on 2025-08-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_price_listing_start_price_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_price',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
